services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Slub\LisztBibliography\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
#  if more than one! class implement the same interface (i.e.Search Interface) read: https://usetypo3.com/dependency-injection/
  Slub\LisztBibliography\Command\IndexCommand:
    tags:
      -
        name: console.command
        command: 'liszt-bibliography:index'
        description: 'Create elasticsearch index from zotero bibliography'
        schedulable: true
